# ---------------------------------------------------------
# The Gradle build expands its project properties to
# replace the substitution tokens.
# ---------------------------------------------------------

info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}
    java:
      source: ${sourceCompatibility}
      target: ${targetCompatibility}

spring:
  main:
    banner-mode: "off"
    web-application-type: "NONE"
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    mapper:
      sort_properties_alphabetically: true

tims:
  tool:
    appScriptName: "./tims"
    apiGatewayUrl: "http://localhost:8180"
    createTestManagementEndpoint: "/api/tms/package/generate"
    translationContentPackageEndpoint: "/api/translation/content-packages"
    sso:
      username: ${tims.tool.sso.username}
      password: ${tims.tool.sso.password}
      clientId: ${tims.tool.sso.client-id}
      clientSecret: ${tims.tool.sso.client-secret}
      grantType: ${tims.tool.sso.grant-type}
      url: ${tims.tool.sso.url}