# ---------------------------------------------------------
# The Gradle build expands its project properties to
# replace the substitution tokens.
# ---------------------------------------------------------

info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}
    java:
      source: ${sourceCompatibility}
      target: ${targetCompatibility}

spring:
  main:
    banner-mode: "off"
    web-application-type: "NONE"
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    mapper:
      sort_properties_alphabetically: true

tims:
  tool:
    appScriptName: "./tims"
    apiGatewayUrl: "http://localhost:8180"
    createTestManagementEndpoint: "/api/tms/package/generate"
    translationContentPackageEndpoint: "/api/translation/content-packages"
    sso:
      username: \${TIMS_TOOL_SSO_USERNAME}
      password: \${TIMS_TOOL_SSO_PASSWORD}
      clientId: \${TIMS_TOOL_SSO_CLIENT_ID}
      clientSecret: \${TIMS_TOOL_SSO_CLIENT_SECRET}
      grantType: \${TIMS_TOOL_SSO_GRANT_TYPE}
      url: \${TIMS_TOOL_SSO_URL}